### ISSUE TITLE
in planetController.UpdateChunks,  dont call Camera.main; 

### ISSUE THREAD

**Issue by Neovariance** [MajorStorm/Planetary-Terrain#1]
Here's a little optimization for you ( probably faster to edit it that me doing a pull request and you merging it :) 

in planetController.UpdateChunks,  don't call Camera.main !
as they say in the official doc:

> This property uses FindGameObjectsWithTag internally and doesn't cache the result. It is advised to cache the return value of Camera.main if it is used multiple times per frame.

**Comment by josephhd** [comment]
Yeah I really should. More than likely in a new version this will be an option to set in the inspector since this gives more control anyways. 

As I have mentioned though, any changes I do make will probably be in a fresh project because coding for ECS and Jobs is structured very differently. Since you are probably curious, these will be primarily how noise is generated. I will post what I have so far in another repo once I have the 3D version sauced out. But this includes generating normals, and implementation with jobs.

**Comment by Neovariance** [comment]
Excellent !

**Comment by Neovariance** [comment]
Any news ? I d like to contribute actively to the new version, if you want it private you can contact me with the email in my github profile !

**Comment by josephhd** [comment]
I've gotten the noise library working. Right now it's written in C (so that
I could use it for other stuff), but is very easy to port over. It computes
the gradient as well, so getting normal information is trivial now
(assuming I did my maths right).

Otherwise, I haven't done much. I've been side tracked with a different
thoughts on how to implement a new version (like a mesh-less rendered), but
I don't think they're really going to pan out.

We can talk about implementation stuff by email. I wasn't able to find your
email, mine should be listed on my github, so just send stuff to that.
