### ISSUE TITLE
No Occlusion Culling

### ISSUE THREAD

**Issue by Neovariance** [MajorStorm/Planetary-Terrain#3]
It seems there is no occlusion culling, that even the other side of the planet is sent to the GPU.

**Comment by josephhd** [comment]
No there isn't. This is because I never implemented it as my knowledge on the subject really wasn't (and still really isn't) up to par. There are a lot of things I want to change about the methodology involved in determining which chunks to actually split, but for now I am leaving it in favor for some optimizations in the mesh generator and noise library (which will probably make their appearance in a completely new version).
